// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmKIY1NEorOxc9lpLMwsJsOvwVaSfNQ9k',
    appId: '1:381873144862:web:7a38103c897dbce9829a0f',
    messagingSenderId: '381873144862',
    projectId: 'reconstroi-jcr',
    authDomain: 'reconstroi-jcr.firebaseapp.com',
    storageBucket: 'reconstroi-jcr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8y01s5FLv1xQiIqDHfdUtQxV3PdDzJb8',
    appId: '1:381873144862:android:de529a5b7f3defb9829a0f',
    messagingSenderId: '381873144862',
    projectId: 'reconstroi-jcr',
    storageBucket: 'reconstroi-jcr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Pxoy3lAiv4O05qpX9oFSJhqVTbA65ts',
    appId: '1:381873144862:ios:2c5dd1bc4dc5aae9829a0f',
    messagingSenderId: '381873144862',
    projectId: 'reconstroi-jcr',
    storageBucket: 'reconstroi-jcr.firebasestorage.app',
    iosClientId: '381873144862-rc51mgrofg668f2mtnt9re9fn26erp1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.reconstroijacarei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Pxoy3lAiv4O05qpX9oFSJhqVTbA65ts',
    appId: '1:381873144862:ios:2c5dd1bc4dc5aae9829a0f',
    messagingSenderId: '381873144862',
    projectId: 'reconstroi-jcr',
    storageBucket: 'reconstroi-jcr.firebasestorage.app',
    iosClientId: '381873144862-rc51mgrofg668f2mtnt9re9fn26erp1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.reconstroijacarei',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmKIY1NEorOxc9lpLMwsJsOvwVaSfNQ9k',
    appId: '1:381873144862:web:ff79782a2ab728f3829a0f',
    messagingSenderId: '381873144862',
    projectId: 'reconstroi-jcr',
    authDomain: 'reconstroi-jcr.firebaseapp.com',
    storageBucket: 'reconstroi-jcr.firebasestorage.app',
  );
}
